-- ESX (default inventory): products lose their metadata without ox_inventory or another metadata inventory.
INSERT IGNORE INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
    ('nz_acid', 'Acid', 1, 0, 1),
    ('nz_addy', 'Addy', 1, 0, 1),
    ('nz_baggie', 'Baggie', 1, 0, 1),
    ('nz_baggie_empty', 'Empty Baggie', 1, 0, 1),
    ('nz_banana', 'Banana', 1, 0, 1),
    ('nz_battery', 'Battery', 1, 0, 1),
    ('nz_bed', 'Mushroom Bed', 6, 0, 1),
    ('nz_cauldron', 'Cauldron', 15, 0, 1),
    ('nz_chem', 'Chemistry Station', 12, 0, 1),
    ('nz_chili', 'Chili', 1, 0, 1),
    ('nz_coca_base', 'Coca Base', 1, 0, 1),
    ('nz_coca_dry', 'Dried Coca Leaf', 1, 0, 1),
    ('nz_coca_leaf', 'Coca Leaf', 1, 0, 1),
    ('nz_cocaine', 'Cocaine', 1, 0, 1),
    ('nz_cuke', 'Cuke', 1, 0, 1),
    ('nz_donut', 'Donut', 1, 0, 1),
    ('nz_energydrink', 'Energy Drink', 1, 0, 1),
    ('nz_fertilizer', 'Fertilizer', 1, 0, 1),
    ('nz_flumedicine', 'Flu Medicine', 1, 0, 1),
    ('nz_gasoline', 'Gasoline', 1, 0, 1),
    ('nz_grainbag', 'Grain Bag', 1, 0, 1),
    ('nz_horsesemen', 'Horse Semen', 1, 0, 1),
    ('nz_iodine', 'Iodine', 1, 0, 1),
    ('nz_jar', 'Jar', 1, 0, 1),
    ('nz_jar_empty', 'Empty Jar', 1, 0, 1),
    ('nz_light', 'Grow Light', 3, 0, 1),
    ('nz_megabean', 'Mega Bean', 1, 0, 1),
    ('nz_meth', 'Meth', 1, 0, 1),
    ('nz_meth_liquid', 'Liquid Meth', 1, 0, 1),
    ('nz_mixer', 'Mixing Station', 9, 0, 1),
    ('nz_motoroil', 'Motor Oil', 1, 0, 1),
    ('nz_mouthwash', 'Mouth Wash', 1, 0, 1),
    ('nz_oven', 'Lab Oven', 12, 0, 1),
    ('nz_packer', 'Packaging Station', 8, 0, 1),
    ('nz_paracetamol', 'Paracetamol', 1, 0, 1),
    ('nz_pgr', 'PGR', 1, 0, 1),
    ('nz_phosphorus', 'Phosphorus', 1, 0, 1),
    ('nz_pot', 'Plastic Pot', 1, 0, 1),
    ('nz_pseudo', 'Pseudo', 1, 0, 1),
    ('nz_rack', 'Drying Rack', 6, 0, 1),
    ('nz_seed_coca', 'Coca Seed', 1, 0, 1),
    ('nz_seed_gdp', 'Granddaddy Purple Seed', 1, 0, 1),
    ('nz_seed_greencrack', 'Green Crack Seed', 1, 0, 1),
    ('nz_seed_ogkush', 'OG Kush Seed', 1, 0, 1),
    ('nz_seed_sourdiesel', 'Sour Diesel Seed', 1, 0, 1),
    ('nz_shroom', 'Shrooms', 1, 0, 1),
    ('nz_shroom_spawn', 'Mushroom Spawn', 1, 0, 1),
    ('nz_soil', 'Soil', 3, 0, 1),
    ('nz_soil_ell', 'Extra Long-Life Soil', 3, 0, 1),
    ('nz_soil_ll', 'Long-Life Soil', 3, 0, 1),
    ('nz_spawnstation', 'Spawn Station', 7, 0, 1),
    ('nz_speedgrow', 'Speed Grow', 1, 0, 1),
    ('nz_spores', 'Spore Syringe', 1, 0, 1),
    ('nz_substrate', 'Mushroom Substrate', 2, 0, 1),
    ('nz_tent', 'Grow Tent', 6, 0, 1),
    ('nz_trimmers', 'Plant Trimmers', 1, 0, 1),
    ('nz_viagra', 'Viagor', 1, 0, 1),
    ('nz_wateringcan', 'Watering Can', 1, 0, 1),
    ('nz_weed', 'Weed', 1, 0, 1);
