-- ox_inventory: paste into ox_inventory/data/items.lua (inside the return table)
-- Product items (weed, meth, baggies, jars...) get their name, quality and effects from metadata.
    ["nz_acid"] = { label = "Acid", weight = 600, stack = true, close = false, description = "Chemistry station ingredient." },
    ["nz_addy"] = { label = "Addy", weight = 30, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_baggie"] = { label = "Baggie", weight = 10, stack = true, close = false, description = "A bagged product." },
    ["nz_baggie_empty"] = { label = "Empty Baggie", weight = 5, stack = true, close = false, description = "Holds 1 unit." },
    ["nz_banana"] = { label = "Banana", weight = 120, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_battery"] = { label = "Battery", weight = 150, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_bed"] = { label = "Mushroom Bed", weight = 6000, stack = true, close = true, description = "Grow mushrooms." },
    ["nz_cauldron"] = { label = "Cauldron", weight = 15000, stack = true, close = true, description = "Turn dried coca leaves into coca base." },
    ["nz_chem"] = { label = "Chemistry Station", weight = 12000, stack = true, close = true, description = "Cook liquid meth." },
    ["nz_chili"] = { label = "Chili", weight = 50, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_coca_base"] = { label = "Coca Base", weight = 50, stack = true, close = false, description = "Bake it in a lab oven." },
    ["nz_coca_dry"] = { label = "Dried Coca Leaf", weight = 10, stack = true, close = false, description = "Cauldron food." },
    ["nz_coca_leaf"] = { label = "Coca Leaf", weight = 15, stack = true, close = false, description = "Dry it on a drying rack." },
    ["nz_cocaine"] = { label = "Cocaine", weight = 10, stack = true, close = false, description = "Loose cocaine." },
    ["nz_cuke"] = { label = "Cuke", weight = 330, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_donut"] = { label = "Donut", weight = 100, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_energydrink"] = { label = "Energy Drink", weight = 330, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_fertilizer"] = { label = "Fertilizer", weight = 1000, stack = true, close = false, description = "+1 quality on the next harvest." },
    ["nz_flumedicine"] = { label = "Flu Medicine", weight = 200, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_gasoline"] = { label = "Gasoline", weight = 1000, stack = true, close = false, description = "Mixing ingredient. Also feeds the cauldron." },
    ["nz_grainbag"] = { label = "Grain Bag", weight = 800, stack = true, close = false, description = "Spawn station ingredient." },
    ["nz_horsesemen"] = { label = "Horse Semen", weight = 200, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_iodine"] = { label = "Iodine", weight = 100, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_jar"] = { label = "Jar", weight = 120, stack = true, close = false, description = "A jar of product." },
    ["nz_jar_empty"] = { label = "Empty Jar", weight = 60, stack = true, close = false, description = "Holds 5 units." },
    ["nz_light"] = { label = "Grow Light", weight = 2500, stack = true, close = true, description = "Plants near it grow faster." },
    ["nz_megabean"] = { label = "Mega Bean", weight = 100, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_meth"] = { label = "Meth", weight = 10, stack = true, close = false, description = "Loose meth." },
    ["nz_meth_liquid"] = { label = "Liquid Meth", weight = 500, stack = true, close = false, description = "Bake it in a lab oven." },
    ["nz_mixer"] = { label = "Mixing Station", weight = 9000, stack = true, close = true, description = "Mix ingredients into your product for new effects." },
    ["nz_motoroil"] = { label = "Motor Oil", weight = 1000, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_mouthwash"] = { label = "Mouth Wash", weight = 400, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_oven"] = { label = "Lab Oven", weight = 12000, stack = true, close = true, description = "Bake liquid meth and coca base." },
    ["nz_packer"] = { label = "Packaging Station", weight = 8000, stack = true, close = true, description = "Bag and jar your product." },
    ["nz_paracetamol"] = { label = "Paracetamol", weight = 50, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_pgr"] = { label = "PGR", weight = 1000, stack = true, close = false, description = "+50% yield on the next harvest." },
    ["nz_phosphorus"] = { label = "Phosphorus", weight = 400, stack = true, close = false, description = "Chemistry station ingredient." },
    ["nz_pot"] = { label = "Plastic Pot", weight = 800, stack = true, close = true, description = "Place it in your lab and grow something." },
    ["nz_pseudo"] = { label = "Pseudo", weight = 200, stack = true, close = false, description = "Chemistry station ingredient." },
    ["nz_rack"] = { label = "Drying Rack", weight = 6000, stack = true, close = true, description = "Dry weed (better quality) and coca leaves." },
    ["nz_seed_coca"] = { label = "Coca Seed", weight = 10, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nz_seed_gdp"] = { label = "Granddaddy Purple Seed", weight = 10, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nz_seed_greencrack"] = { label = "Green Crack Seed", weight = 10, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nz_seed_ogkush"] = { label = "OG Kush Seed", weight = 10, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nz_seed_sourdiesel"] = { label = "Sour Diesel Seed", weight = 10, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nz_shroom"] = { label = "Shrooms", weight = 10, stack = true, close = false, description = "Loose mushrooms." },
    ["nz_shroom_spawn"] = { label = "Mushroom Spawn", weight = 400, stack = true, close = false, description = "Mix it into a mushroom bed." },
    ["nz_soil"] = { label = "Soil", weight = 3000, stack = true, close = false, description = "Basic soil. Good for one harvest." },
    ["nz_soil_ell"] = { label = "Extra Long-Life Soil", weight = 3000, stack = true, close = false, description = "Good for three harvests, best quality." },
    ["nz_soil_ll"] = { label = "Long-Life Soil", weight = 3000, stack = true, close = false, description = "Good for two harvests, better quality." },
    ["nz_spawnstation"] = { label = "Spawn Station", weight = 7000, stack = true, close = true, description = "Inject spores into grain bags." },
    ["nz_speedgrow"] = { label = "Speed Grow", weight = 1000, stack = true, close = false, description = "Instantly grows a plant by half." },
    ["nz_spores"] = { label = "Spore Syringe", weight = 50, stack = true, close = false, description = "Spawn station ingredient." },
    ["nz_substrate"] = { label = "Mushroom Substrate", weight = 2000, stack = true, close = false, description = "Fills a mushroom bed." },
    ["nz_tent"] = { label = "Grow Tent", weight = 6000, stack = true, close = true, description = "A pot in a tent with its own light. Grows faster." },
    ["nz_trimmers"] = { label = "Plant Trimmers", weight = 300, stack = true, close = false, description = "For harvesting." },
    ["nz_viagra"] = { label = "Viagor", weight = 30, stack = true, close = false, description = "Mixing ingredient." },
    ["nz_wateringcan"] = { label = "Watering Can", weight = 600, stack = true, close = false, description = "Fill it at a tap." },
    ["nz_weed"] = { label = "Weed", weight = 10, stack = true, close = false, description = "Loose weed." },
