-- Dumps the shared config to web/preview-data.js for the browser previews (no FiveM needed).
-- lua5.4 tests/export_config.lua <resource dir>
local root = arg[1] or '.'
local function v(x, y, z, w) return { x = x, y = y, z = z, w = w } end
vec2, vec3, vec4, vector3 = v, v, v, v
function IsDuplicityVersion() return false end
function GetCurrentResourceName() return 'nayzeee-drugempire' end
for _, f in ipairs({ 'config/main.lua', 'config/products.lua', 'config/stations.lua', 'config/customers.lua', 'config/shops.lua' }) do
    dofile(root .. '/' .. f)
end
local function enc(x)
    local t = type(x)
    if t == 'table' then
        if #x > 0 or next(x) == nil then
            local o = {}
            for i = 1, #x do o[i] = enc(x[i]) end
            return '[' .. table.concat(o, ',') .. ']'
        end
        local o, keys = {}, {}
        for k in pairs(x) do keys[#keys + 1] = tostring(k) end
        table.sort(keys)
        for _, k in ipairs(keys) do
            local val = x[k]; if val == nil then val = x[tonumber(k)] end
            if type(val) ~= 'function' then o[#o + 1] = string.format('%q', k) .. ':' .. enc(val) end
        end
        return '{' .. table.concat(o, ',') .. '}'
    elseif t == 'string' then return string.format('%q', x):gsub('\\\n', '\\n')
    elseif t == 'number' or t == 'boolean' then return tostring(x) end
    return 'null'
end
local items = {}
for k, row in pairs(Config.Items) do items[k] = row[1] end
local out = io.open(root .. '/web/preview-data.js', 'w')
out:write('/* generated by tests/export_config.lua - browser preview only */\nwindow.PREVIEW_CFG = ')
out:write(enc({ ui = Config.UI, effects = Config.Effects, quality = Config.Quality, standards = Config.Standards, items = items,
    ingredients = Config.Ingredients, drugs = Config.Drugs, maxEffects = Config.Mixing.maxEffects, mixSeconds = 2,
    regions = Config.Regions, spots = Config.Spots, customers = Config.Customers, dealers = Config.DealerList, shops = Config.Shops,
    drops = Config.DeadDrops, kinds = Config.Kinds, phone = { name = Config.Phone.AppName } }))
out:write(';\n')
out:close()
print('wrote web/preview-data.js')
