-- ESX (default inventory): products lose their metadata without ox_inventory or another metadata inventory.
INSERT IGNORE INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
    ('nzw_baggie', 'Baggie of Weed', 1, 0, 1),
    ('nzw_baggie_empty', 'Empty Baggie', 1, 0, 1),
    ('nzw_brick', 'Brick of Weed', 1, 0, 1),
    ('nzw_brickpress', 'Brick Press', 40, 0, 1),
    ('nzw_dryrack', 'Drying Rack', 7, 0, 1),
    ('nzw_fertilizer', 'Fertilizer', 1, 0, 1),
    ('nzw_growtent', 'Grow Tent', 9, 0, 1),
    ('nzw_ing_addy', 'Addy', 1, 0, 1),
    ('nzw_ing_banana', 'Banana', 1, 0, 1),
    ('nzw_ing_battery', 'Battery', 1, 0, 1),
    ('nzw_ing_chili', 'Chili', 1, 0, 1),
    ('nzw_ing_cuke', 'Cuke', 1, 0, 1),
    ('nzw_ing_donut', 'Donut', 1, 0, 1),
    ('nzw_ing_energydrink', 'Energy Drink', 1, 0, 1),
    ('nzw_ing_flumedicine', 'Flu Medicine', 1, 0, 1),
    ('nzw_ing_gasoline', 'Gasoline', 1, 0, 1),
    ('nzw_ing_horsesemen', 'Horse Semen', 1, 0, 1),
    ('nzw_ing_iodine', 'Iodine', 1, 0, 1),
    ('nzw_ing_megabean', 'Mega Bean', 1, 0, 1),
    ('nzw_ing_motoroil', 'Motor Oil', 1, 0, 1),
    ('nzw_ing_mouthwash', 'Mouth Wash', 1, 0, 1),
    ('nzw_ing_paracetamol', 'Paracetamol', 1, 0, 1),
    ('nzw_ing_viagra', 'Viagor', 1, 0, 1),
    ('nzw_jar', 'Jar of Weed', 1, 0, 1),
    ('nzw_jar_empty', 'Empty Jar', 1, 0, 1),
    ('nzw_light_fullspec', 'Full Spectrum Grow Light', 5, 0, 1),
    ('nzw_light_halogen', 'Halogen Grow Light', 4, 0, 1),
    ('nzw_light_led', 'LED Grow Light', 3, 0, 1),
    ('nzw_mixstation', 'Mixing Station', 18, 0, 1),
    ('nzw_packstation', 'Packaging Station', 15, 0, 1),
    ('nzw_pgr', 'Plant Growth Regulator', 1, 0, 1),
    ('nzw_pot', 'Plastic Pot', 1, 0, 1),
    ('nzw_rack', 'Suspension Rack', 8, 0, 1),
    ('nzw_seed_acagold', 'Acapulco Gold Seed', 1, 0, 1),
    ('nzw_seed_colomgold', 'Colombian Gold Seed', 1, 0, 1),
    ('nzw_seed_dosidos', 'Do-Si-Dos Seed', 1, 0, 1),
    ('nzw_seed_lemonskunk', 'Lemon Skunk Seed', 1, 0, 1),
    ('nzw_seed_nlights', 'Northern Lights Seed', 1, 0, 1),
    ('nzw_seed_ogkush', 'OG Kush Seed', 1, 0, 1),
    ('nzw_seed_rainbowb', 'Rainbow Belts Seed', 1, 0, 1),
    ('nzw_soil', 'Potting Soil', 6, 0, 1),
    ('nzw_soil_premium', 'Premium Potting Soil', 6, 0, 1),
    ('nzw_speedgrow', 'Speed Growth', 1, 0, 1),
    ('nzw_trimmers', 'Trimmers', 1, 0, 1),
    ('nzw_wateringcan', 'Watering Can', 1, 0, 1),
    ('nzw_weed', 'Weed', 1, 0, 1);
