-- ox_inventory: paste into ox_inventory/data/items.lua (inside the return table)
-- Product items (weed, baggies, jars, bricks) get their strain, quality and effects from metadata.
    ["nzw_baggie"] = { label = "Baggie of Weed", weight = 10, stack = true, close = false, description = "A sealed baggie." },
    ["nzw_baggie_empty"] = { label = "Empty Baggie", weight = 5, stack = true, close = false, description = "Holds 1 unit." },
    ["nzw_brick"] = { label = "Brick of Weed", weight = 1000, stack = true, close = false, description = "A pressed brick." },
    ["nzw_brickpress"] = { label = "Brick Press", weight = 40000, stack = true, close = true, description = "Industrial brick press used to squish stuff into bricks." },
    ["nzw_dryrack"] = { label = "Drying Rack", weight = 7000, stack = true, close = true, description = "Hang up organic items here to improve their quality." },
    ["nzw_fertilizer"] = { label = "Fertilizer", weight = 1000, stack = true, close = false, description = "Spray on a growing plant: +1 quality." },
    ["nzw_growtent"] = { label = "Grow Tent", weight = 9000, stack = true, close = true, description = "A small grow tent with built-in lighting and pot. Plants will grow faster but smaller." },
    ["nzw_ing_addy"] = { label = "Addy", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Thought-Provoking." },
    ["nzw_ing_banana"] = { label = "Banana", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Gingeritis." },
    ["nzw_ing_battery"] = { label = "Battery", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Bright-Eyed." },
    ["nzw_ing_chili"] = { label = "Chili", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Spicy." },
    ["nzw_ing_cuke"] = { label = "Cuke", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Energizing." },
    ["nzw_ing_donut"] = { label = "Donut", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Calorie-Dense." },
    ["nzw_ing_energydrink"] = { label = "Energy Drink", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Athletic." },
    ["nzw_ing_flumedicine"] = { label = "Flu Medicine", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Sedating." },
    ["nzw_ing_gasoline"] = { label = "Gasoline", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Toxic." },
    ["nzw_ing_horsesemen"] = { label = "Horse Semen", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Long Faced." },
    ["nzw_ing_iodine"] = { label = "Iodine", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Jennerising." },
    ["nzw_ing_megabean"] = { label = "Mega Bean", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Foggy." },
    ["nzw_ing_motoroil"] = { label = "Motor Oil", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Slippery." },
    ["nzw_ing_mouthwash"] = { label = "Mouth Wash", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Balding." },
    ["nzw_ing_paracetamol"] = { label = "Paracetamol", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Sneaky." },
    ["nzw_ing_viagra"] = { label = "Viagor", weight = 150, stack = true, close = false, description = "Mixing ingredient. Adds Tropic Thunder." },
    ["nzw_jar"] = { label = "Jar of Weed", weight = 140, stack = true, close = false, description = "A sealed jar." },
    ["nzw_jar_empty"] = { label = "Empty Jar", weight = 120, stack = true, close = false, description = "Holds 5 units." },
    ["nzw_light_fullspec"] = { label = "Full Spectrum Grow Light", weight = 4500, stack = true, close = true, description = "Very fancy full-spectrum grow light. Stimulates plant growth 30% faster than halogen. Must be placed on a suspension rack." },
    ["nzw_light_halogen"] = { label = "Halogen Grow Light", weight = 3500, stack = true, close = true, description = "Cheap and simple halogen grow light. Must be placed on a suspension rack." },
    ["nzw_light_led"] = { label = "LED Grow Light", weight = 3000, stack = true, close = true, description = "A simple LED grow light. Emits a purple light that stimulates plant growth 15% faster than halogen. Must be placed on a suspension rack." },
    ["nzw_mixstation"] = { label = "Mixing Station", weight = 18000, stack = true, close = true, description = "Used to mix product with ingredients to create unique new products." },
    ["nzw_packstation"] = { label = "Packaging Station", weight = 15000, stack = true, close = true, description = "Provides a clean surface to place product into packaging." },
    ["nzw_pgr"] = { label = "Plant Growth Regulator", weight = 1000, stack = true, close = false, description = "Plant growth regulator (PGR) will increase the yields of your plants, at the cost of quality." },
    ["nzw_pot"] = { label = "Plastic Pot", weight = 900, stack = true, close = true, description = "A pot for one plant. Add soil, then a seed." },
    ["nzw_rack"] = { label = "Suspension Rack", weight = 8000, stack = true, close = true, description = "Used to hang grow lights above pots." },
    ["nzw_seed_gdp"] = { label = "Granddaddy Purple Seed", weight = 5, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nzw_seed_goldleaf"] = { label = "Gold Leaf Seed", weight = 5, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nzw_seed_greencrack"] = { label = "Green Crack Seed", weight = 5, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nzw_seed_lemonhaze"] = { label = "Lemon Haze Seed", weight = 5, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nzw_seed_ogkush"] = { label = "OG Kush Seed", weight = 5, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nzw_seed_purplepunch"] = { label = "Purple Punch Seed", weight = 5, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nzw_seed_sourdiesel"] = { label = "Sour Diesel Seed", weight = 5, stack = true, close = false, description = "Plant it in a pot with soil." },
    ["nzw_soil"] = { label = "Potting Soil", weight = 6000, stack = true, close = false, description = "Enough soil for one plant." },
    ["nzw_soil_premium"] = { label = "Premium Potting Soil", weight = 6000, stack = true, close = false, description = "Better soil: higher quality, lasts two harvests." },
    ["nzw_speedgrow"] = { label = "Speed Growth", weight = 1000, stack = true, close = false, description = "Instantly grows the plant by 50%, but reduces plant quality." },
    ["nzw_trimmers"] = { label = "Trimmers", weight = 150, stack = true, close = false, description = "For harvesting buds." },
    ["nzw_wateringcan"] = { label = "Watering Can", weight = 800, stack = true, close = false, description = "Fill it at the tap in your lab. Four waterings per fill." },
    ["nzw_weed"] = { label = "Weed", weight = 2, stack = true, close = false, description = "A trimmed bud. Package it, dry it or mix it." },
