-- Only for ESX WITHOUT ox_inventory. The default ESX inventory has no metadata,
-- so wigs and bundles there are generic (no tiers, styles, pictures, wearing or listings). ox_inventory is strongly recommended.
INSERT IGNORE INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
    ('wig', 'Wig', 1, 0, 1),
    ('hair_bundle', 'Hair Bundle', 1, 0, 1),
    ('wig_cap', 'Wig Cap', 1, 0, 1),
    ('hair_dye', 'Hair Dye', 1, 0, 1),
    ('wig_glue', 'Lace Glue', 1, 0, 1),
    ('wig_kit', 'Wig Kit', 1, 0, 1),
    ('scissors', 'Scissors', 1, 0, 1),
    ('hair_clippers', 'Hair Clippers', 1, 0, 1),
    ('straight_razor', 'Straight Razor', 1, 0, 1),
    ('zip_ties', 'Zip Ties', 1, 0, 1),
    ('hair_remover', 'Hair Remover', 1, 0, 1),
    ('relaxer', 'Lye Relaxer', 1, 0, 1),
    ('lice_jar', 'Lice Jar', 1, 0, 1),
    ('mud_bag', 'Bag of Mud', 1, 0, 1),
    ('shampoo', 'Shampoo', 1, 0, 1),
    ('regrowth_oil', 'Regrowth Oil', 1, 0, 1),
    ('wigtableblue', 'Blue Wig Table', 1, 0, 1),
    ('wigtablepink', 'Pink Wig Table', 1, 0, 1),
    ('wigtablepurp', 'Purple Wig Table', 1, 0, 1),
    ('wigtablered', 'Red Wig Table', 1, 0, 1),
    ('hair_weft', 'Hair Weft', 1, 0, 1),
    ('wig_thread', 'Weaving Thread', 1, 0, 1),
    ('lace_closure', '5x5 HD Closure', 1, 0, 1),
    ('lace_frontal', '13x4 HD Frontal', 1, 0, 1),
    ('lace_full', 'Full Lace Unit', 1, 0, 1);
