#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════
   NAYZEEE ICONS · build
   node icons/build.js
   Reads icons/src/icons.js and writes:
     icons/svg/<name>.svg     one file per icon
     icons/nz-icons.svg       sprite  → <svg class="nzi-svg"><use href="nz-icons.svg#car"/></svg>
     icons/nz-icons.css       classes → <i class="nzi nzi-car"></i>
     icons/nz-icons-fa.css    Font Awesome names → NAYZEEE icons (<i class="fa-solid fa-car">)
     icons/nz-icons.data.js   metadata for the cheatsheet
     core/nz-core.js          the built-in NZ.icon() set (between the ICONS markers)
   No dependencies.
   ═══════════════════════════════════════════════════════════ */
const fs = require('fs');
const path = require('path');
const ROOT = __dirname;
const { icons, alias } = require('./src/icons.js');

const ATTRS = 'fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="miter"';

// accent elements read --nzi-accent (falls back to the icon colour)
const accent = svg => svg.replace(/<(\w+) class="a"([^>]*?)(\/?)>/g, (m, tag, rest, close) =>
  /fill="currentColor"/.test(rest)
    ? `<${tag} class="a"${rest} style="fill:var(--nzi-accent,currentColor)"${close}>`
    : `<${tag} class="a"${rest} style="stroke:var(--nzi-accent,currentColor)"${close}>`);

// checks
const seen = new Set();
for (const i of icons) {
  if (seen.has(i.name)) throw new Error(`duplicate icon: ${i.name}`);
  seen.add(i.name);
}
for (const [a, t] of Object.entries(alias)) {
  if (!seen.has(t)) throw new Error(`alias ${a} → unknown icon ${t}`);
  if (seen.has(a)) throw new Error(`alias ${a} clashes with an icon name`);
}

const out = p => path.join(ROOT, p);
fs.rmSync(out('svg'), { recursive: true, force: true });
fs.mkdirSync(out('svg'), { recursive: true });

/* one file per icon */
for (const i of icons) {
  fs.writeFileSync(out(`svg/${i.name}.svg`),
    `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" ${ATTRS}>${accent(i.svg)}</svg>\n`);
}

/* sprite — stroke settings come from the <svg class="nzi-svg"> that uses it */
fs.writeFileSync(out('nz-icons.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n` +
  icons.map(i => `<symbol id="${i.name}" viewBox="0 0 24 24">${accent(i.svg)}</symbol>`).join('\n') +
  '\n' + Object.entries(alias).map(([a, t]) => `<symbol id="${a}" viewBox="0 0 24 24"><use href="#${t}"/></symbol>`).join('\n') +
  '\n</svg>\n');

/* CSS mask classes */
const uri = svg => `url("data:image/svg+xml,${
  `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23000' stroke-width='1.75' stroke-linecap='round' stroke-linejoin='miter'>${svg}</svg>`
    .replace(/"/g, "'").replace(/currentColor/g, '%23000').replace(/#/g, '%23').replace(/</g, '%3C').replace(/>/g, '%3E')
}")`;
const byName = Object.fromEntries(icons.map(i => [i.name, i]));
const HEAD = `/* NAYZEEE ICONS — generated by icons/build.js, edit icons/src/icons.js instead.
   <i class="nzi nzi-car"></i>   sizes: nzi-xs nzi-sm nzi-lg nzi-xl nzi-2x nzi-3x   extras: nzi-fw nzi-spin
   Icons take the text colour and the font size, like an icon font. */\n`;
const base = `display:inline-block;flex:none;width:1em;height:1em;vertical-align:-.14em;background-color:currentColor;` +
  `-webkit-mask:var(--nzi) center/contain no-repeat;mask:var(--nzi) center/contain no-repeat`;
let css = HEAD +
  `.nzi{${base}}\n` +
  `.nzi-xs{font-size:.75em}.nzi-sm{font-size:.875em}.nzi-lg{font-size:1.33em;vertical-align:-.25em}.nzi-xl{font-size:1.5em;vertical-align:-.3em}` +
  `.nzi-2x{font-size:2em}.nzi-3x{font-size:3em}.nzi-fw{width:1.25em}\n` +
  `.nzi-spin{animation:nzi-spin 1.2s linear infinite}@keyframes nzi-spin{to{transform:rotate(360deg)}}\n` +
  `/* sprite usage: <svg class="nzi-svg"><use href="nz-icons.svg#car"/></svg> */\n` +
  `.nzi-svg{display:inline-block;flex:none;width:1em;height:1em;vertical-align:-.14em;fill:none;stroke:currentColor;stroke-width:1.75;stroke-linecap:round;stroke-linejoin:miter}\n` +
  `.nzi-duo{--nzi-accent:#08afa2}\n`;
for (const i of icons) css += `.nzi-${i.name}{--nzi:${uri(i.svg)}}\n`;
for (const [a, t] of Object.entries(alias)) css += `.nzi-${a}{--nzi:${uri(byName[t].svg)}}\n`;
fs.writeFileSync(out('nz-icons.css'), css);

/* Font Awesome compatibility: first icon to claim an FA name wins */
const fa = new Map();
for (const i of icons) for (const f of i.fa) if (!fa.has(f)) fa.set(f, i.name);
const sel = [...fa.keys()].map(f => `.fa-${f}`);
let facss = `/* NAYZEEE ICONS — Font Awesome compatibility, generated by icons/build.js.
   Load this AFTER Font Awesome (or without it). Existing markup like
   <i class="fa-solid fa-car"></i> then shows the NAYZEEE icon instead.
   FA names not listed here keep rendering from Font Awesome. */\n` +
  `${sel.join(',')}{${base};font-size:inherit;line-height:1}\n` +
  `${sel.map(s => s + '::before').join(',')}{content:none!important}\n`;
for (const [f, name] of fa) facss += `.fa-${f}{--nzi:${uri(byName[name].svg)}}\n`;
fs.writeFileSync(out('nz-icons-fa.css'), facss);

/* cheatsheet data */
fs.writeFileSync(out('nz-icons.data.js'),
  '/* generated by icons/build.js */\nwindow.NZ_ICON_DATA = ' +
  JSON.stringify({ icons: icons.map(i => ({ name: i.name, cat: i.cat, tags: i.tags, fa: i.fa, svg: accent(i.svg) })), alias }) + ';\n');

/* core runtime icons */
const corePath = path.join(ROOT, '..', 'core', 'nz-core.js');
let core = fs.readFileSync(corePath, 'utf8');
const START = '  /* ICONS:START — generated by icons/build.js, edit icons/src/icons.js */';
const END = '  /* ICONS:END */';
const block = START + '\n  const ICONS = {\n' +
  icons.map(i => `    '${i.name}':'${accent(i.svg).replace(/'/g, "\\'")}',`).join('\n') +
  '\n  };\n  Object.entries(' + JSON.stringify(alias) + ').forEach(([a, t]) => { ICONS[a] = ICONS[t]; });\n' + END;
if (core.includes(START)) {
  core = core.slice(0, core.indexOf(START)) + block + core.slice(core.indexOf(END) + END.length);
} else {
  const m = core.match(/  \/\* ── stroke icons, 24×24 ── \*\/\n  const ICONS = \{[\s\S]*?\n  \};/);
  if (!m) throw new Error('could not find the ICONS block in core/nz-core.js');
  core = core.replace(m[0], block);
}
fs.writeFileSync(corePath, core);

const kb = f => (fs.statSync(out(f)).size / 1024).toFixed(1) + ' KB';
console.log(`${icons.length} icons + ${Object.keys(alias).length} aliases, ${fa.size} Font Awesome names`);
console.log(`nz-icons.css ${kb('nz-icons.css')} · nz-icons.svg ${kb('nz-icons.svg')} · nz-icons-fa.css ${kb('nz-icons-fa.css')}`);
