-- Paste into qb-core/shared/items.lua (QBShared.Items = { ... })

heist_tablet = { name = 'heist_tablet', label = 'Heist Tablet', weight = 500, type = 'item', image = 'heist_tablet.png', unique = false, useable = true, shouldClose = true, description = 'Opens the heist tablet' },
lockpick = { name = 'lockpick', label = 'Advanced Lockpick', weight = 200, type = 'item', image = 'lockpick.png', unique = false, useable = false, shouldClose = true, description = 'Store, house and car jobs' },
heist_drill = { name = 'heist_drill', label = 'Heavy Drill', weight = 4000, type = 'item', image = 'heist_drill.png', unique = false, useable = false, shouldClose = true, description = 'Drills vaults, ATMs and safes' },
angle_grinder = { name = 'angle_grinder', label = 'Angle Grinder', weight = 3000, type = 'item', image = 'angle_grinder.png', unique = false, useable = false, shouldClose = true, description = 'Cuts locks and containers' },
heavy_rope = { name = 'heavy_rope', label = 'Tow Rope', weight = 1500, type = 'item', image = 'heavy_rope.png', unique = false, useable = false, shouldClose = true, description = 'Rip an ATM off the wall' },
hacking_device = { name = 'hacking_device', label = 'Hacking Device', weight = 400, type = 'item', image = 'hacking_device.png', unique = false, useable = false, shouldClose = true, description = 'Splice into ATMs and payphones' },
safepad = { name = 'safepad', label = 'SafePad', weight = 600, type = 'item', image = 'safepad.png', unique = false, useable = false, shouldClose = true, description = 'Cracks vault panels' },
heist_laptop = { name = 'heist_laptop', label = 'Encrypted Laptop', weight = 1500, type = 'item', image = 'heist_laptop.png', unique = false, useable = false, shouldClose = true, description = 'High-end vault exploits' },
gps_jammer = { name = 'gps_jammer', label = 'GPS Jammer', weight = 500, type = 'item', image = 'gps_jammer.png', unique = false, useable = false, shouldClose = true, description = 'Kills vehicle trackers' },
heist_drone = { name = 'heist_drone', label = 'Recon Drone', weight = 2000, type = 'item', image = 'heist_drone.png', unique = false, useable = true, shouldClose = true, description = 'Flyable recon / payload drone' },
thermite = { name = 'thermite', label = 'Thermite Charge', weight = 800, type = 'item', image = 'thermite.png', unique = false, useable = false, shouldClose = true, description = 'Burns through gates' },
c4_charge = { name = 'c4_charge', label = 'C4 Charge', weight = 900, type = 'item', image = 'c4_charge.png', unique = false, useable = false, shouldClose = true, description = 'Breaching charge' },
gasmask = { name = 'gasmask', label = 'Gas Mask', weight = 600, type = 'item', image = 'gasmask.png', unique = false, useable = true, shouldClose = true, description = 'Toggle your gas mask' },
heist_bag = { name = 'heist_bag', label = 'Duffel Bag', weight = 800, type = 'item', image = 'heist_bag.png', unique = false, useable = false, shouldClose = true, description = 'Heist duffel bag' },
gold_bar = { name = 'gold_bar', label = 'Gold Bar', weight = 2000, type = 'item', image = 'gold_bar.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
diamond = { name = 'diamond', label = 'Loose Diamond', weight = 50, type = 'item', image = 'diamond.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
rolex = { name = 'rolex', label = 'Luxury Watch', weight = 100, type = 'item', image = 'rolex.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
gold_chain = { name = 'gold_chain', label = 'Gold Chain', weight = 100, type = 'item', image = 'gold_chain.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
diamond_ring = { name = 'diamond_ring', label = 'Diamond Ring', weight = 50, type = 'item', image = 'diamond_ring.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
necklace = { name = 'necklace', label = 'Necklace', weight = 100, type = 'item', image = 'necklace.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
painting = { name = 'painting', label = 'Painting', weight = 3000, type = 'item', image = 'painting.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
electronics = { name = 'electronics', label = 'Electronics', weight = 500, type = 'item', image = 'electronics.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
laptop = { name = 'laptop', label = 'Laptop', weight = 1500, type = 'item', image = 'laptop.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
coke_brick = { name = 'coke_brick', label = 'Cocaine Brick', weight = 1000, type = 'item', image = 'coke_brick.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
weed_brick = { name = 'weed_brick', label = 'Weed Brick', weight = 1000, type = 'item', image = 'weed_brick.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
weapon_parts = { name = 'weapon_parts', label = 'Weapon Parts', weight = 800, type = 'item', image = 'weapon_parts.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
data_drive = { name = 'data_drive', label = 'Encrypted Drive', weight = 100, type = 'item', image = 'data_drive.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
cargo_crate = { name = 'cargo_crate', label = 'Sealed Cargo', weight = 8000, type = 'item', image = 'cargo_crate.png', unique = false, useable = false, shouldClose = true, description = 'Sell to a fence' },
