-- Paste into ox_inventory/data/items.lua

['heist_tablet'] = { label = 'Heist Tablet', weight = 500, stack = true, close = true, description = 'Opens the heist tablet' },
['lockpick'] = { label = 'Advanced Lockpick', weight = 200, stack = true, close = true, description = 'Store, house and car jobs' },
['heist_drill'] = { label = 'Heavy Drill', weight = 4000, stack = true, close = true, description = 'Drills vaults, ATMs and safes' },
['angle_grinder'] = { label = 'Angle Grinder', weight = 3000, stack = true, close = true, description = 'Cuts locks and containers' },
['heavy_rope'] = { label = 'Tow Rope', weight = 1500, stack = true, close = true, description = 'Rip an ATM off the wall' },
['hacking_device'] = { label = 'Hacking Device', weight = 400, stack = true, close = true, description = 'Splice into ATMs and payphones' },
['safepad'] = { label = 'SafePad', weight = 600, stack = true, close = true, description = 'Cracks vault panels' },
['heist_laptop'] = { label = 'Encrypted Laptop', weight = 1500, stack = true, close = true, description = 'High-end vault exploits' },
['gps_jammer'] = { label = 'GPS Jammer', weight = 500, stack = true, close = true, description = 'Kills vehicle trackers' },
['heist_drone'] = { label = 'Recon Drone', weight = 2000, stack = true, close = true, description = 'Flyable recon / payload drone' },
['thermite'] = { label = 'Thermite Charge', weight = 800, stack = true, close = true, description = 'Burns through gates' },
['c4_charge'] = { label = 'C4 Charge', weight = 900, stack = true, close = true, description = 'Breaching charge' },
['gasmask'] = { label = 'Gas Mask', weight = 600, stack = true, close = true, description = 'Toggle your gas mask' },
['heist_bag'] = { label = 'Duffel Bag', weight = 800, stack = true, close = true, description = 'Heist duffel bag' },
['gold_bar'] = { label = 'Gold Bar', weight = 2000, stack = true, close = true, description = 'Sell to a fence' },
['diamond'] = { label = 'Loose Diamond', weight = 50, stack = true, close = true, description = 'Sell to a fence' },
['rolex'] = { label = 'Luxury Watch', weight = 100, stack = true, close = true, description = 'Sell to a fence' },
['gold_chain'] = { label = 'Gold Chain', weight = 100, stack = true, close = true, description = 'Sell to a fence' },
['diamond_ring'] = { label = 'Diamond Ring', weight = 50, stack = true, close = true, description = 'Sell to a fence' },
['necklace'] = { label = 'Necklace', weight = 100, stack = true, close = true, description = 'Sell to a fence' },
['painting'] = { label = 'Painting', weight = 3000, stack = true, close = true, description = 'Sell to a fence' },
['electronics'] = { label = 'Electronics', weight = 500, stack = true, close = true, description = 'Sell to a fence' },
['laptop'] = { label = 'Laptop', weight = 1500, stack = true, close = true, description = 'Sell to a fence' },
['coke_brick'] = { label = 'Cocaine Brick', weight = 1000, stack = true, close = true, description = 'Sell to a fence' },
['weed_brick'] = { label = 'Weed Brick', weight = 1000, stack = true, close = true, description = 'Sell to a fence' },
['weapon_parts'] = { label = 'Weapon Parts', weight = 800, stack = true, close = true, description = 'Sell to a fence' },
['data_drive'] = { label = 'Encrypted Drive', weight = 100, stack = true, close = true, description = 'Sell to a fence' },
['cargo_crate'] = { label = 'Sealed Cargo', weight = 8000, stack = true, close = true, description = 'Sell to a fence' },
