-- ESX (items table). Run once in your database.
INSERT IGNORE INTO `items` (`name`, `label`, `weight`) VALUES
  ('heist_tablet', 'Heist Tablet', 1),
  ('lockpick', 'Advanced Lockpick', 1),
  ('heist_drill', 'Heavy Drill', 4),
  ('angle_grinder', 'Angle Grinder', 3),
  ('heavy_rope', 'Tow Rope', 1),
  ('hacking_device', 'Hacking Device', 1),
  ('safepad', 'SafePad', 1),
  ('heist_laptop', 'Encrypted Laptop', 1),
  ('gps_jammer', 'GPS Jammer', 1),
  ('heist_drone', 'Recon Drone', 2),
  ('thermite', 'Thermite Charge', 1),
  ('c4_charge', 'C4 Charge', 1),
  ('gasmask', 'Gas Mask', 1),
  ('heist_bag', 'Duffel Bag', 1),
  ('gold_bar', 'Gold Bar', 2),
  ('diamond', 'Loose Diamond', 1),
  ('rolex', 'Luxury Watch', 1),
  ('gold_chain', 'Gold Chain', 1),
  ('diamond_ring', 'Diamond Ring', 1),
  ('necklace', 'Necklace', 1),
  ('painting', 'Painting', 3),
  ('electronics', 'Electronics', 1),
  ('laptop', 'Laptop', 1),
  ('coke_brick', 'Cocaine Brick', 1),
  ('weed_brick', 'Weed Brick', 1),
  ('weapon_parts', 'Weapon Parts', 1),
  ('data_drive', 'Encrypted Drive', 1),
  ('cargo_crate', 'Sealed Cargo', 8);
